name: "MERGE SUBSCRIPTION"

on:
  push:
    paths:
      - 'config.php'
      - 'index.php'      
      - '.github/workflows/main.yml'

  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          
      - name: Execute PHP script
        run: |
          php index.php
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "🚀 Done! - $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M:%S')"
          git push
