name: Random-Lines

on:
  push:
    paths:
      - 'random_lines.py'
      - '.github/workflows/random.yml'

  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run script to select random lines
      run: |
          python random_lines.py

    - name: Push Random
      if: steps.changesRandom.outputs.changed == 'true'
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add lite
          timestamp=$(TZ='Asia/Tehran' date)
          git commit -m "✅Updated on ${timestamp}"
          git push

    - name: Convert Random to base64
      run: |
          > lite64
          content=$(cat lite | base64 | tr -d '\n')
            echo "$content" > lite64

    - name: Check for Random base64 Changes
      id: changesRandom64
      run: |
            git diff --quiet && echo 'No changes' || echo '::set-output name=changed::true'
            
    - name: Push Random Base64
      if: steps.changesRandom64.outputs.changed == 'true'
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          timestamp=$(TZ='Asia/Tehran' date)
          git commit -m "✅Updated on ${timestamp}"
          git push
